[package]
name = "swaynimated"
version = "0.1.0"
authors = ["Elyhaka <57923898+Elyhaka@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winit = "0.20.0-alpha4"
image = "0.22.3"

[dependencies.wgpu]
version = "0.4.0"
features = [ "vulkan" ]